# Generated by Django 3.1.3 on 2022-01-30 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название урока')),
                ('cabinet', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['cabinet'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница')], max_length=50, verbose_name='День')),
                ('slug', models.SlugField(help_text='Здесь ничего не трогать, заполняется автоматически', verbose_name='URL')),
                ('eigth_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eigth', to='forms.lesson', verbose_name='Восьмой урок')),
                ('fifth_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fifth', to='forms.lesson', verbose_name='Пятый урок')),
                ('first_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first', to='forms.lesson', verbose_name='Первый урок')),
                ('fourth_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fourth', to='forms.lesson', verbose_name='Четвертый урок')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.form', verbose_name='Класс')),
                ('second_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second', to='forms.lesson', verbose_name='Второй урок')),
                ('seventh_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seventh', to='forms.lesson', verbose_name='Седьмой урок')),
                ('sixth_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sixth', to='forms.lesson', verbose_name='Шестой урок')),
                ('third_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='third', to='forms.lesson', verbose_name='Третий урок')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя ученика')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.form', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
