# Generated by Django 3.1.3 on 2021-05-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210528_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name'], 'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, choices=[('русский язык и литература', 'Русский язык и Литература'), ('румынский', 'Румынский язык и литература'), ('английский', 'Английский язык'), ('украинский', 'Украинский язык и литература'), ('история', 'История румын и всеобщая история'), ('география', 'География'), ('биология', 'Биология'), ('информатика', 'информатика'), ('химия', 'Химия'), ('физика', 'Физика'), ('математика', 'Математика'), ('физкультура', 'Физическое воспитание')], max_length=100, null=True, verbose_name='Предмет'),
        ),
    ]
