# Generated by Django 3.1.3 on 2021-08-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20210812_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('русский язык и литература', 'Русский язык и Литература'), ('Румынский язык и литература', 'Румынский язык и литература'), ('Английский язык', 'Английский язык'), ('Украинский язык и литература', 'Украинский язык и литература'), ('История румын и всеобщая история', 'История румын и всеобщая история'), ('география', 'География'), ('биология', 'Биология'), ('информатика', ' Информатика'), ('химия', 'Химия'), ('физика', 'Физика'), ('математика', 'Математика'), ('Физическое воспитание', 'Физическое воспитание')], max_length=100, verbose_name='Предмет'),
        ),
    ]
