# Generated by Django 3.1.3 on 2021-12-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20210812_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='slug',
        ),
    ]
